# Generated by Django 5.1.3 on 2025-01-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('feedback_or_suggestion', models.TextField()),
                ('related_department', models.CharField(max_length=100)),
            ],
        ),
    ]
