# Generated by Django 5.1.3 on 2025-01-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='type',
            field=models.CharField(choices=[('DSF', 'Deep Seafood'), ('ROF', 'Royal Future')], default='DSF', max_length=255),
        ),
    ]
