# Generated by Django 5.1.3 on 2025-01-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='insight',
            options={'ordering': ['department'], 'verbose_name': 'Feedback And Suggestion', 'verbose_name_plural': 'Feedbacks And Suggestions'},
        ),
    ]
