# Generated by Django 5.1.3 on 2025-01-15 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_brand_alter_insight_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
