# Generated by Django 5.1.3 on 2025-01-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_insight_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/insight_images'),
        ),
    ]
