# Generated by Django 5.1.4 on 2025-01-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0004_insight_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='insight_images'),
        ),
    ]
