# Generated by Django 5.1.4 on 2025-01-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0006_branch_insight_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
    ]
