# Generated by Django 5.1.3 on 2025-01-28 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0007_alter_branch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='insight',
            name='related_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insights.department'),
        ),
    ]
