# Generated by Django 5.1.3 on 2025-01-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0008_department_alter_insight_related_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='type',
            field=models.CharField(choices=[('DSF', 'Deep Seafood'), ('ROF', 'Royal Future'), ('QAR', 'Qatar')], default='DSF', max_length=255),
        ),
    ]
